// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// 从环境变量中读取配置
const supabaseUrl = process.env.SUPABASE_URL || import.meta.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_PUBLISHABLE_KEY || import.meta.env.SUPABASE_PUBLISHABLE_KEY;

// 如果环境变量缺失，则抛出错误
if (!supabaseUrl || !supabaseKey) {
  throw new Error('Missing Supabase configuration. Please set SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY.');
}

// 创建 Supabase 客户端
export const supabase = createClient<Database>(supabaseUrl, supabaseKey);

// Mock functions to simulate database operations without actual DB tables
export const mockDB = {
  from: (table: string) => ({
    select: (columns: string = '*') => ({
      eq: (column: string, value: any) => ({
        single: async () => ({ data: null, error: null })
      }),
      limit: (limit: number) => ({
        eq: (column: string, value: any) => ({
          data: null,
          error: null
        })
      })
    }),
    insert: (data: any) => ({
      data: null,
      error: null
    }),
    update: (data: any) => ({
      eq: (column: string, value: any) => ({
        data: null,
        error: null
      })
    })
  })
};

// Override supabase methods to avoid errors
const originalFrom = supabase.from.bind(supabase);
supabase.from = (table: string) => {
  try {
    return originalFrom(table as any);
  } catch (error) {
    console.warn(`Table ${table} doesn't exist in schema, using mock`);
    return mockDB.from(table) as any;
  }
};
